package com.vsu.unit_test_generator.util;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class FileManager {
    private static final String suffix = "AutoGeneratedTest.java";

    public boolean isExistGeneratedTests(String filename, String path) {
        return Files.exists(Path.of(path + filename + suffix));
    }

    private void providePath(Path path) {
        try {
            Files.createDirectories(path);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void provideFile(String path, String filename) {
        if (!isExistGeneratedTests(filename, path)){
            try {
                Files.createFile(Path.of(path + filename + suffix));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    private Path getPathTest(Path path) {
        String template = path.toString().replace("main", "test");
        return Path.of(template);
    }
//
//    private File provideFile(String path, String filename) {
////        while (Files.exists(pa))
////        path = Path.of(path)
////        exists(Path path);
//        return null;
//    }
//
//    private
//
//    public boolean writeFile(StringBuilder testClass, File file) {
//        try (FileWriter writer = new FileWriter(file);) {
//            writer.write(testClass.toString());
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//        return false;
//    }
}
